export enum RoleEnum {
  GET_ROLE = 'get-role',
  GET_GROUP = 'get-group',
  GET_GROUP_DETAIL = 'get-group-detail',
  CREATE_ROLE = 'create-role',
  CREATE_GROUP = 'create-group',
  GET_BLACK_LIST = 'get-black-list',
  CREATE_BLACK_LIST = 'create-black-list',
  UPDATE_FLAG = 'update-flag',
  DELETE_BLACK_LIST = 'delete-black-list',
  REPORT_USERS = 'report-users',
  REPORT_USERS_EXPORT = 'report-users-export',
  REPORT_TRANSACTION = 'report-transactions',
  REPORT_MERCHANT = 'report-merchant ',
  STATE_BANK = 'state-bank',
  STATE_BANK_EXPORT = 'state-bank-export',
  REPORT_TRANSACTION_CHART = 'report-transactions-chart',
  REPORT_TRANSACTION_SUCCESS = 'report-transactions-success',
  REPORT_TRANSACTION_FAIL = 'report-transactions-fail',
  REPORT_BANK = 'report-bank',
  GET_USERS = 'get-user',
  PUT_USERS = 'put-user',
  CREATE_CASE = 'create-case',
  EXPORT_CASE = 'export-case',
  ASSIGN_CASE = 'assign-case',
  GET_METABASE = 'get-metabase',
  GET_CASE = 'get-case',
  REPORT_CASE = 'report-case',
  REPORT_EXPORT_CASE = 'report-export-case',
  UPDATE_CASE = 'update-case',
  UPDATE_CASE_MANAGE = 'update-case-manage',
  DELETE_CASE = 'delete-case',
  CALL_ASTERISK = 'call-asterisk',
  GET_ASTERISK = 'get-asterisk',
}

export enum RoleGroupEnum {
  ADMIN = 'admin',
}
